### ISSUE TITLE
Verbindungsauskunft mit Ankunftszeit gibt Verbindungen nach gewünschter Ankunftszeit zurück

### ISSUE THREAD

**Issue by tobiasfabian** [mobidata-bw/TRIAS#13]
Anfrage: Ich möchte von A nach B fahren und um 15:00 Uhr ankommen.  
Rückgabe: Verbindungen mit Ankunftszeit **nach** 15:00 Uhr.  
Erwartet Rückgabe: Verbindungen mit Ankunftszeit **vor** 15:00 Uhr.  

Übersetzt in eine TripRequest-Anfrage schaut das beispielsweise so aus:

### Request
```xml
<TripRequest>
  <Origin>
    <LocationRef>
      <StopPointRef>de:08111:6115</StopPointRef>
    </LocationRef>
  </Origin>
  <Destination>
    <LocationRef>
      <StopPointRef>de:08415:22006</StopPointRef>
    </LocationRef>
    <DepArrTime>2024-03-04T15:00:00+01:00</DepArrTime>
  </Destination>
  <Params>
    <NumberOfResultsAfter>3</NumberOfResultsAfter>
  </Params>
</TripRequest>
```

### Response

Es werden `TripResult`-Element mit einer `EndTime` zurückgegeben, die nach 15:00 Uhr (*DepArrTime* `2024-03-04T15:00:00+01:00`) liegen. Z.B. 15:11 Uhr (*trias:EndTime*`2024-03-04T14:11:00Z`) 

```xml
<trias:TripResult>
  <trias:ResultId>ID-775BA002-4D0E-4F80-BE5B-C43B9B5B3AD2</trias:ResultId>
  <trias:Trip>
    <trias:TripId>ID-775BA002-4D0E-4F80-BE5B-C43B9B5B3AD2</trias:TripId>
    <trias:Duration>PT48M</trias:Duration>
    <trias:StartTime>2024-03-04T13:23:00Z</trias:StartTime>
    <trias:EndTime>2024-03-04T14:11:00Z</trias:EndTime>
    <trias:Interchanges>0</trias:Interchanges>
    <trias:Distance>56556</trias:Distance>
    <trias:TripLeg>
      <trias:LegId>1</trias:LegId>
      <trias:TimedLeg>
        <trias:LegBoard>
          // …
        </trias:LegBoard>
        <trias:LegAlight>
          <trias:StopPointRef>de:08415:22006:3:2</trias:StopPointRef>
          <trias:StopPointName>
            <trias:Text>Reutlingen Hauptbahnhof</trias:Text>
            <trias:Language>de</trias:Language>
          </trias:StopPointName>
          <trias:PlannedBay>
            <trias:Text>2</trias:Text>
            <trias:Language>de</trias:Language>
          </trias:PlannedBay>
          <trias:ServiceArrival>
            <trias:TimetabledTime>2024-03-04T14:11:00Z</trias:TimetabledTime>
            <trias:EstimatedTime>2024-03-04T14:11:00Z</trias:EstimatedTime>
          </trias:ServiceArrival>
          <trias:StopSeqNumber>8</trias:StopSeqNumber>
        </trias:LegAlight>
        <trias:Service>
          // …
        </trias:Service>
      </trias:TimedLeg>
    </trias:TripLeg>
  </trias:Trip>
</trias:TripResult>
```

----

Meiner Meinung nach sollten nur Verbindungen mit einer Ankunftszeit **vor** 15:00 Uhr zurückgegeben werden. Oder übersehe ich etwas?

In der Spezifikation heißt es zu **DepArrTime** (7.6.16): *Beabsichtigte Abfahrts- oder Ankunftszeit an dem in
Location oder TripLocation bezeichneten Ort.*

----

Das Problem kann auf folgender Seite nachvollzogen werden:  
[reutlinger-stadtverkehr.de/fahrplaene/verbindungsauskunft](https://reutlinger-stadtverkehr.de/fahrplaene/verbindungsauskunft?from=Stuttgart%2C+Hauptbahnhof&fromData=%7B%22type%22%3A%22stop%22%2C%22id%22%3A%22de%3A08111%3A6115%22%2C%22name%22%3A%22Stuttgart%2C+Hauptbahnhof%22%2C%22geoPosition%22%3A%7B%22longitude%22%3A%229.18279%22%2C%22latitude%22%3A%2248.78488%22%7D%7D&to=Reutlingen%2C+Hauptbahnhof&toData=%7B%22type%22%3A%22stop%22%2C%22id%22%3A%22de%3A08415%3A22006%22%2C%22name%22%3A%22Reutlingen%2C+Hauptbahnhof%22%2C%22geoPosition%22%3A%7B%22longitude%22%3A%229.20951%22%2C%22latitude%22%3A%2248.49643%22%7D%7D&datetimeFor=arrival&date=2024-05-29&time=15%3A00)

**Comment by GerdC** [comment]
(ich bin nur ein Anwender)

Meines Erachtens ist `<NumberOfResultsAfter>3</NumberOfResultsAfter>` an der Stelle undefiniert und wird deshalb ignoriert.

Korrekt müsste sein: als Parameter...
**Entweder** `<NumberOfResults>` mitgeben.
**Oder** `<NumberOfResultsGroup>` mitgeben innerhalb dieses Elements sowohl `<NumberOfResultsBefore>` als auch `<NumberOfResultsAfter>` mitgeben.

Bei dem Ergebnis, das du haben willst, solltest du `<NumberOfResultsBefore>` füllen.

**Comment by tobiasfabian** [comment]
Tausend Dank.

Genau das ist die Lösung des Problems. Ich haben einfach konsequent den Parameter `NumberOfResultsAfter` übersehen.
